#!/bin/bash

MONGO_ADMIN_USER="$1"
MONGO_ADMIN_PASSWORD="$2"
FILE=$3
BASE=$(echo "$FILE" | xargs basename)

MONGO_PORT=${MONGO_PORT:-27017}
MONGO_SETUP_PORT=$((MONGO_PORT + 1))

MONGO_DATABASE=${MONGO_INITDB_DATABASE:-test}

if [[ "${MONGO_ADMIN_USER}" != " " && "${MONGO_ADMIN_PASSWORD}" != " " ]]; then
  MONGO_AUTH_OPTIONS="-u ${MONGO_ADMIN_USER} -p ${MONGO_ADMIN_PASSWORD} --authenticationDatabase admin"
fi

if (echo "$BASE" | grep '.json.gz$'); then
  COLLECTION=${BASE%.json.gz}
  gzip -dc ${FILE} | mongoimport \
    --host localhost \
    --port ${MONGO_SETUP_PORT} \
    --db ${MONGO_DATABASE} \
    --jsonArray \
    --collection "${COLLECTION}" \
    --numInsertionWorkers 4 \
    ${MONGO_AUTH_OPTIONS}
elif (echo "$BASE" | grep '.json$'); then
  COLLECTION=${BASE%.json}
  cat ${FILE} | mongoimport \
    --host localhost \
    --port ${MONGO_SETUP_PORT} \
    --db ${MONGO_DATABASE} \
    --jsonArray \
    --collection "${COLLECTION}" \
    --numInsertionWorkers 4 \
    ${MONGO_AUTH_OPTIONS}
elif (echo "$BASE" | grep '.js$'); then
  mongo localhost:${MONGO_SETUP_PORT}/${MONGO_DATABASE} \
    ${MONGO_AUTH_OPTIONS} \
    ${FILE}
fi

